package net.sachau.deathcrawl;

public enum Event {
    NEWGAME,
    RANDOMPARTY,
    PARTYDONE,
    STARTTURN,
    STARTENCOUNTER,
    STARTCARDPHASE,
    ENDCARDPHASE, STARTENCOUNTERVIEW, EXPERIENCEPHASE, PARTYMOVE, CHARACTERDEATH, GAMEOVER,

}
